# 禁用原生 RGB 装饰背光（避免编译冲突并省电）
CONFIG_ZMK_RGB_UNDERGLOW=n
CONFIG_PWM=y

# 启用智能 RGB 状态指示小部件
CONFIG_SMART_RGBLED_WIDGET=y

# 配置电量报警阈值：临界电量低于 20% 时进行红灯闪烁报警
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_CRITICAL=20
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_LOW=20
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_HIGH=80
