# dux34 Configuration

# Required: Allow P0.09 and P0.10 (NFC pins) to be used as regular GPIO
# col6 = P0.10 (D16), col7 = P0.09 (D10)
CONFIG_NFCT_PINS_AS_GPIOS=y

# Bluetooth TX power
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
